"""empty message

Revision ID: 02288100a51a
Revises: 0b3e888b0085
Create Date: 2026-03-03 14:40:09.343252

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "02288100a51a"
down_revision: Union[str, Sequence[str], None] = "0b3e888b0085"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
