"""empty message

Revision ID: 0b3e888b0085
Revises: fa94a59c98c3
Create Date: 2026-03-03 14:33:01.428804

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0b3e888b0085"
down_revision: Union[str, Sequence[str], None] = "fa94a59c98c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
