"""empty message

Revision ID: 674245793145
Revises: 4c08b30ef89e
Create Date: 2026-03-03 13:12:29.793026

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "674245793145"
down_revision: Union[str, Sequence[str], None] = "4c08b30ef89e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
