"""empty message

Revision ID: cdd490491edc
Revises: 674245793145
Create Date: 2026-03-03 13:25:52.588031

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "cdd490491edc"
down_revision: Union[str, Sequence[str], None] = "674245793145"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
