"""empty message

Revision ID: d180d3cb6990
Revises: 02288100a51a
Create Date: 2026-03-03 14:43:24.675512

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d180d3cb6990"
down_revision: Union[str, Sequence[str], None] = "02288100a51a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
