"""empty message

Revision ID: fa94a59c98c3
Revises: cdd490491edc
Create Date: 2026-03-03 13:32:56.812131

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fa94a59c98c3"
down_revision: Union[str, Sequence[str], None] = "cdd490491edc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
